
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://dokeliddgqvotqmisfir.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRva2VsaWRkZ3F2b3RxbWlzZmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwODI5MDAsImV4cCI6MjA0ODY1ODkwMH0.syzZsH1CZ24VqfbJZsTMgNUfpOlx4pwgTvBtoRh5CqA";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);
